@host=localhost
@port=3000

###
GET  {{host}}:{{port}}/api/chats
Content-Type: application/json

###
POST  {{host}}:{{port}}/api/chats
Content-Type: application/json

{
    "mensagem": "teste mensagem"
}
